name: Auto accept/reject pull requests

on:
  issues:
    types: [labeled]

jobs:
  auto_handle_playlists:
    name: Accept or reject playlist
    if: ${{ contains(github.event.issue.labels.*.name,'playlist') && !contains(github.event.issue.state,'close') }}

    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write

    env:
      TITLE: ${{ github.event.issue.title }}
      PLAYLIST: ${{ github.event.issue.body }}

    steps:
      - uses: actions/checkout@v1
      - name: Create JSON
        run: ./.github/scripts/create_playlist.sh
      - name: Validate JSON
        id: validation
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: template.json
          INPUT_JSONS: playlists/${{ github.event.issue.title }}.json
      - name: Push playlist
        env:
          INVALID: ${{ steps.validation.outputs.invalid }}
        run: ./.github/scripts/push.sh
