name: Auto accept/reject pull requests

on:
  issues:
    types: [opened, labeled]

jobs:
  auto_handle_playlists:
    name: Accept or reject playlist
    if: ${{ contains(github.event.issue.labels.*.name,'playlist') && !contains(github.event.issue.labels.*.name,'closed') }}

    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      
    env: 
      TITLE: ${{ github.event.issue.labels.title }}
      PLAYLIST: ${{ github.event.issue.labels.body }}

    steps:
      - uses: actions/checkout@v1
      - run: TITLE="$TITLE" PLAYLIST="$PLAYLIST" chmod +x .github/scripts/*.sh && ./.github/scripts/verify.sh && ./.github/scripts/push.sh
