name: Auto accept/reject pull requests

on:
  issues:
    types: [labeled]

jobs:
  auto_handle_playlists:
    name: Accept or reject playlist
    if: ${{ contains(github.event.issue.labels.*.name,'playlist') && !contains(github.event.issue.state,'close') }}

    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write

    steps:
      - uses: actions/checkout@v1
      - env:
          TITLE: ${{ github.event.issue.title }}
          PLAYLIST: ${{ github.event.issue.body }}
        run: chmod +x .github/scripts/*.sh && ./.github/scripts/verify.sh && ./.github/scripts/push.sh
